default_config:

ocpp:
  default_authorization_status: 'Invalid'
  authorization_list:
    - id_tag: '12345678'
      name: 'My tag'
      authorization_status : Accepted
    - id_tag: 'CAFEBABE'
      name: 'Some other tag'
      authorization_status: Blocked
    - id_tag: 'DEADBEEF'
      name: 'Old tag'
      status: Expired
    - id_tag: '12341234'
      name: 'Invalid tag'
      authorization_status: Invalid

logger:
  default: info
  logs:
    custom_components.ocpp: debug

# If you need to debug uncomment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
# debugpy:
