name: Linting

on:
  push:
    branches:
      - main
      - master
      - dev
  pull_request:

env:
  DEFAULT_PYTHON: "3.13"

jobs:
  pre-commit:
    runs-on: "ubuntu-latest"
    name: Pre-commit
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        uses: actions/setup-python@v5.6.0
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}

      - name: Upgrade pip
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install "$(grep '^uv' < requirements.txt)"
          pip --version

      - name: Install Python modules
        run: |
          . venv/bin/activate
          uv pip install "$(grep '^pre-commit' < requirements.txt)"

      - name: Run pre-commit on all files
        run: |
          . venv/bin/activate
          pre-commit run --all-files --show-diff-on-failure --color=always

  hacs:
    runs-on: "ubuntu-latest"
    name: HACS
    steps:
      - name: Check out the repository
        uses: "actions/checkout@v4"

      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"
          ignore: brands

  hassfest:
    runs-on: "ubuntu-latest"
    name: Hassfest
    steps:
      - name: Check out the repository
        uses: "actions/checkout@v4"

      - name: Hassfest validation
        uses: "home-assistant/actions/hassfest@master"
  tests:
    runs-on: "ubuntu-latest"
    name: Run tests
    environment: continuous-integration
    steps:
      - name: Check out code from GitHub
        uses: "actions/checkout@v4"
      - name: Setup Python ${{ env.DEFAULT_PYTHON }}
        uses: "actions/setup-python@v5.6.0"
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
      - name: Install requirements
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install "$(grep '^uv' < requirements.txt)"
          uv pip install -r requirements.txt --prerelease=allow
      - name: Tests suite
        run: |
          . venv/bin/activate
          pytest \
            --cov=./ \
            --cov-report=xml \
            --cov-report=term \
            --timeout=30 \
            --durations=10 \
            -n auto \
            -p no:sugar \
            -rA \
            tests
      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
